WIP Get all groups
zahodi/bovine-inventory pull request #17
Opened 2017-01-07 00:33 UTC by zahodi

2017-01-27 06:57 UTC, senorsmile requested changes
more changes to come

2017-01-27 06:57 UTC, senorsmile commented on lib/bovine/staticinventory.py
> +    groups_directory = self.root_directory + 'groups/'
this may be the fix, although I can't get tox to work on this stupid mac.  test/test2.py works successfully for me.

2017-02-08 02:01 UTC, zahodi reviewed
So are you saying that the loop doesn't work or that the merge function doesn't work unless it's python3.5?

2017-02-09 06:37 UTC, senorsmile commented
> So are you saying that the loop doesn't work or that the merge function doesn't work unless it's python3.5?

What is this question in response to?

2017-03-30 05:37 UTC, senorsmile requested changes
only one change really needed

2017-03-30 05:37 UTC, senorsmile commented on test/test_data/static/hosts/main.yml
> +    foo2: bar2
the file name must always match the hostname... so this file should be called host1.yml

2017-03-30 05:37 UTC, senorsmile commented on lib/bovine/inventory.py
> +#!/usr/bin/env python3
rename!  sounds good to me

2017-04-12 22:23 UTC, senorsmile commented
get all groups and hosts now working.  need tests.

2017-04-13 05:10 UTC, merged